server:
  port: 3344

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}/${spring.application.name}
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:8170/eureka/

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的服务名称
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/TenYearWood/springcloud-config.git  #GitHub上复制的项目地址
          search-paths:  #搜索目录
            - springcloud-config
      label: master   #读取分支